### PR TITLE
bsc#816746: Do not add conf file entries for virtual interfaces

### PR DESCRIPTION
**Pull request by mmnelemane**
Solves bug: #816746.

Does not add .conf file in /etc/dhcp3/hosts.d/ for virtual interfaces. So no accumulation of conf files in crowbar node for each VM. Constant interfaces (like bridges, physical interfaces) will continue to hold .conf file in this path.

### CODE REVIEW

**Comment by rsalevsky** [comment]
Wrong repo please submit first to https://github.com/crowbar/crowbar-core.

**Comment by mmnelemane** [comment]
Its already submitted to https://github.com/crowbar/crowbar-core. 
This is a backport.

**Comment by mmnelemane** [comment]
Pull request for cloud6
https://github.com/crowbar/crowbar-core/pull/12

**Comment by rsalevsky** [comment]
Also a backport goes to https://github.com/crowbar/barclamp-provisioner.

**Pull request closed without merging**
